Attribute VB_Name = "modConstants"
Option Explicit

' RoadReviewer / Site Inspector Review Tool - shared constants.
' Single place for product ids, sheet names, Sites column indices,
' named-range names, URL templates and the FHWA FunctionalSystem domain.
' Friction point #9 (mixing column letters and indices) is resolved by
' using 1-based column index constants everywhere.
'
' Two products are built from this one src/ tree (see build\build.ps1):
'   Standard  -> RoadReviewer.xlsm            (PDMGs / partners / reviewers)
'   Inspector -> Site Inspector Review Tool.xlsm (full site-inspector kit)
' The product id is baked into the workbook at build time as a hidden
' defined name (NM_PRODUCT) via modUtil.SetProduct.

' ---- Products ----
Public Const PRODUCT_STANDARD As String = "Standard"
Public Const PRODUCT_INSPECTOR As String = "Inspector"
' Hidden workbook-level defined name that stores which product this file is.
Public Const NM_PRODUCT As String = "RR_Product"

' Version stamp shown on Start Here + the Sources sheet so a shared copy can
' be traced back to the PR / build it came from. Bump this on each release.
Public Const BUILD_REFERENCE As String = "PR #21"

' ---- Sheet names ----
Public Const SH_START As String = "Start Here"
Public Const SH_SITES As String = "Sites"
Public Const SH_SOURCES As String = "Sources"
' Generated by PrepareMapPages (inspector product). Not a control sheet -
' BuildWorkbook should NOT recreate it; PrepareMapPages owns its lifecycle.
Public Const SH_MAPPAGES As String = "MapPages"

' ---- Start Here named ranges ----
' WO/DI/Disaster/Applicant/Buffer are inspector-only; the standard product
' never creates them. Shared code reads them via modUtil.SetupValue, which
' returns "" for a missing name, so every consumer already degrades cleanly.
Public Const NR_WO As String = "JobWO"
Public Const NR_DI As String = "JobDI"
Public Const NR_DISASTER As String = "JobDisaster"
Public Const NR_APPLICANT As String = "JobApplicant"
Public Const NR_STATE As String = "JobState"
Public Const NR_OUTFOLDER As String = "JobOutputFolder"
' Optional - when the user pastes an ArcGIS Online webmap URL here, the
' Sites table's "AGOL Map" column (COL_AGOLMAP) produces per-row deep-links
' that open the webmap centered on the row's coordinates.
Public Const NR_AGOLMAP As String = "JobAgolMap"
' Search radius (in feet) used when the exact point-on-polyline intersect
' returns no road segments. The classifier always tries an exact intersect
' first; this buffer is the second-chance fallback. Default 200 ft (read
' from Start Here, capped to [1, 1000] in modClassify.BufferFeet). The
' standard product has no cell for it and always runs on the default.
Public Const NR_BUFFER As String = "JobBufferFeet"
Public Const DEFAULT_BUFFER_FEET As Long = 200

' ---- Sites table geometry ----
' Row 1 is a slim toolbar (hint text + Check Roads / Photo Links buttons)
' so the paste -> classify -> review loop never has to leave the sheet.
Public Const SITES_TOOLBAR_ROW As Long = 1
Public Const SITES_HEADER_ROW As Long = 2
Public Const SITES_FIRST_DATA_ROW As Long = 3
Public Const SITES_FORMULA_ROWS As Long = 500   ' hyperlink/validation pre-fill depth

' ---- Sites column indices (1-based) ----
' Order is optimized for copy-paste: Latitude | Longitude | Description are
' contiguous so a three-column paste from any spreadsheet lands in one go.
' Address sits to the RIGHT of Description because it is rarely used (it
' only feeds the geocoder when lat/lon are blank).
Public Const COL_WO As Long = 1          ' inspector-only (hidden in standard)
Public Const COL_DI As Long = 2          ' inspector-only (hidden in standard)
Public Const COL_SITENO As Long = 3
Public Const COL_SITENAME As Long = 4
Public Const COL_LAT As Long = 5
Public Const COL_LON As Long = 6
Public Const COL_DESC As Long = 7
Public Const COL_ADDRESS As Long = 8
Public Const COL_CATEGORY As Long = 9
' Two optional user-data columns. Both flow into the KML description tag,
' the MapPages textbox stamp, and the CSV export - anywhere Description
' shows up - when they have values.
Public Const COL_COSTS As Long = 10
Public Const COL_WORKCOMP As Long = 11
Public Const COL_GEOCODE As Long = 12
Public Const COL_GMAP As Long = 13
Public Const COL_STREETVIEW As Long = 14
Public Const COL_BING As Long = 15
Public Const COL_GEARTH As Long = 16
Public Const COL_FEMAVIEW As Long = 17
Public Const COL_FIRMPORTAL As Long = 18
Public Const COL_NFCMAP As Long = 19
Public Const COL_CLASS As Long = 20
Public Const COL_URBANRURAL As Long = 21
Public Const COL_ACUBNAME As Long = 22
Public Const COL_ROADNAME As Long = 23
' Street name(s) from the U.S. Census Bureau's TIGERweb Local Roads layer.
' Dense (covers most addresses) where COL_ROADNAME / MDOT 543 only gets
' trunkline route designations like "I-94 BL". Pipe-joined when multiple
' streets fall inside the search buffer (intersection points).
Public Const COL_STREET As Long = 24
Public Const COL_ELIGIBILITY As Long = 25
Public Const COL_FIRMSTATUS As Long = 26  ' inspector-only (hidden in standard)
Public Const COL_MAPSTATUS As Long = 27   ' inspector-only (hidden in standard)
' Per-row deep-link into the user's own AGOL webmap (Start Here NR_AGOLMAP).
' Empty cell when NR_AGOLMAP isn't set, so the column is unobtrusive when
' nobody has wired up an AGOL map.
Public Const COL_AGOLMAP As Long = 28
Public Const COL_LAST As Long = 28

' ---- Verification map URL templates (§4.3). {LAT}/{LON} substituted at run time. ----
Public Const URL_GMAP As String = "https://www.google.com/maps?q={LAT},{LON}"
Public Const URL_STREETVIEW As String = "https://www.google.com/maps?q&layer=c&cbll={LAT},{LON}"
Public Const URL_BING As String = "https://www.bing.com/maps?cp={LAT}~{LON}&lvl=18&style=h"
' Google Earth web - includes the historical-imagery slider, the main
' pre-disaster-condition source users asked for by name.
Public Const URL_GEARTH As String = "https://earth.google.com/web/search/{LAT},{LON}"
Public Const URL_FEMAVIEW As String = "https://fema.maps.arcgis.com/apps/mapviewer/index.html?find={LON}%2C{LAT}&marker={LON},{LAT},4326&level=16"
Public Const URL_FIRMPORTAL As String = "https://msc.fema.gov/portal/firmette?latitude={LAT}&longitude={LON}"
' Open the FEMA-hosted NFC/ACUB webmap (item 6a1702b9147243d1a5ee62cd614bc681)
' in ArcGIS Online Map Viewer, centered + markered on the row's point.
' The previous link pointed at the MDOT Experience app, whose popup chrome
' blocked the inspector from clicking through to the actual damage point;
' the FEMA webmap is the same data without the experience's UI wrapper.
'
' (Tried appending &visibleLayers=NfcNhsPub_8332,193df725e5e-layer-20 to
' force only NFC + ACUB on by default. The new Map Viewer choked on the
' URL — the webmap didn't load at all. Reverted. Realistic fix is to
' save a custom webmap in AGOL with the two layers preset visible and
' point this URL there instead.)
Public Const URL_NFC_MAPVIEW As String = "https://fema.maps.arcgis.com/apps/mapviewer/index.html?webmap=6a1702b9147243d1a5ee62cd614bc681&center={LON},{LAT}&level=16&marker={LON},{LAT}"

' Indiana and Wisconsin don't have a curated combined NFC+ACUB webmap the
' way MI does, so these side-load the state's own live NFC FeatureServer
' (§4.2a/§4.2b) directly into the same FEMA Map Viewer base URL + params
' already proven working for URL_FEMAVIEW above (find=/marker=/level=)
' rather than the webmap=+center= combination that broke when a
' visibleLayers param was added (see the note above). Degrades gracefully
' even if the Map Viewer version in use doesn't render the `url=` layer -
' the pin+zoom still resolves correctly either way.
Public Const URL_NFC_MAPVIEW_IN As String = "https://fema.maps.arcgis.com/apps/mapviewer/index.html?url=https%3A%2F%2Fgisdata.in.gov%2Fserver%2Frest%2Fservices%2FHosted%2FLRSE_Functional_Class%2FFeatureServer%2F22&find={LON}%2C{LAT}&marker={LON},{LAT},4326&level=16"
Public Const URL_NFC_MAPVIEW_WI As String = "https://fema.maps.arcgis.com/apps/mapviewer/index.html?url=https%3A%2F%2Fservices5.arcgis.com%2F0pgGLzT0Nh7FVjon%2Farcgis%2Frest%2Fservices%2FFFCL_gdb%2FFeatureServer%2F3&find={LON}%2C{LAT}&marker={LON},{LAT},4326&level=16"

' ---- REST endpoints (§4.1, §4.2, §8.2) ----
Public Const REST_FIRMETTE As String = "https://msc.fema.gov/arcgis/rest/services/NFHL_Print/MSCPrintB/GPServer/PrintFIRMette"
Public Const REST_MDOT_NFC As String = "https://mdotgis.state.mi.us/arcgis/rest/services/Widget/NextGenPrFinderPub/FeatureServer/353"
Public Const REST_MDOT_ROUTE As String = "https://mdotgis.state.mi.us/arcgis/rest/services/Widget/NextGenPrFinderPub/FeatureServer/543"
Public Const REST_ACUB As String = "https://services.arcgis.com/xOi1kZaI0eWDREZv/arcgis/rest/services/NTAD_Adjusted_Urban_Areas/FeatureServer/0"

' Indiana NFC (§4.2a). LRSE_Functional_Class carries the bare FHWA 1-7 code
' (field functional_class) with no urban/rural embedded - same shape as MDOT
' 353. Road name is NOT on this layer (no shared LRS join key), so it's a
' separate point-intersect query against the statewide centerline layer.
Public Const REST_IN_NFC As String = "https://gisdata.in.gov/server/rest/services/Hosted/LRSE_Functional_Class/FeatureServer/22"
Public Const REST_IN_ROADNAME As String = "https://gisdata.in.gov/server/rest/services/Hosted/Road_Centerlines_of_Indiana_2021/FeatureServer/15"

' Wisconsin NFC (§4.2b) - two layers, queried in sequence. The State Trunk
' Network (interstates/state highways) carries a bare FHWA 1-7 code
' (FED_FC_CD, string) plus its own separate URB_TYPE field (unused - ACUB
' stays the single urban/rural source of truth per §4.2). When no state-trunk
' segment intersects, fall back to the Local Road Network snapshot, whose
' FNCT_CLS_CTGY_TYCD field encodes urban/rural INTO the class code and needs
' WisconsinLocalCategoryToFhwa() below to normalize back to bare FHWA 1-7.
Public Const REST_WI_STATE_TRUNK As String = "https://services5.arcgis.com/0pgGLzT0Nh7FVjon/arcgis/rest/services/FFCL_gdb/FeatureServer/3"
Public Const REST_WI_LOCAL_ROADS As String = "https://services5.arcgis.com/0pgGLzT0Nh7FVjon/arcgis/rest/services/WI_Local_Roads_Flood_Damage_Assessment_Snapshot/FeatureServer/1"
Public Const REST_CENSUS_GEOCODE As String = "https://geocoding.geo.census.gov/geocoder/locations/onelineaddress"
' U.S. Census Bureau TIGERweb — Local Roads (full detail layer 8 of the
' Transportation MapServer). Returns the NAME field for any street whose
' centerline intersects the search buffer. Covers every state, free, no
' auth. We hit this in addition to MDOT 543 because MDOT only carries
' designated trunkline routes — TIGER fills in the local street names.
Public Const REST_TIGER_ROADS As String = "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/Transportation/MapServer/8"

' MDOT requires a browser User-Agent or it returns HTTP 403 (§4.2 operational note).
Public Const BROWSER_UA As String = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"

' ---- State selector (F8). MI/IN/WI NFC layers are wired in V1; MN/IL/OH are placeholders. ----
Public Const STATE_LIST As String = "WI,IN,MI,MN,IL,OH"

' ---- Status-prefix used by the "re-run failed rows" feature (F12). ----
Public Const STATUS_FAILED_PREFIX As String = "Failed - "

' ---- FEMA Print FIRMette GP-job polling (inspector product) ----
Public Const FIRMETTE_POLL_INTERVAL_SECONDS As Long = 2
Public Const FIRMETTE_POLL_MAX_ATTEMPTS As Long = 90    ' ~3 min max

' ---- MapPages layout (inspector product, ported from prototype) ----
' MAP_ROWS_PER_PAGE = 4 large rows of ~153pt each. With page height 612pt
' (landscape Letter) that fills a single page exactly. The merged A:M
' region per page hosts the pasted screenshot; the textbox sits on top.
Public Const MAP_ROWS_PER_PAGE As Long = 4
Public Const MAP_COLS_WIDE As Long = 13
Public Const MAP_PAGE_HEIGHT_PTS As Double = 612    ' Landscape Letter
Public Const MAP_PAGE_WIDTH_PTS As Double = 792
Public Const MAP_TEXTBOX_WIDTH As Double = 230
Public Const MAP_TEXTBOX_HEIGHT As Double = 80

' Returns the FHWA functional-class label for a bare FHWA 1-7 code. MDOT
' (layer 353, LrseFunctionalSystem domain), Indiana (LRSE_Functional_Class,
' dFunctionalClass domain) and Wisconsin (FED_FC_CD, plus the local-roads
' layer once normalized by WisconsinLocalCategoryToFhwa) all share this same
' numeric FHWA standard, so one label table covers all three wired states
' (§4.2). Code 0 only comes out of Michigan's domain ("Non-Certified
' Roadway") or an unrecognized Wisconsin local-road category - both fall
' into FederalAidVerdict's "review manually" bucket rather than a verdict.
Public Function FunctionalSystemLabel(ByVal code As Long) As String
    Select Case code
        Case 0: FunctionalSystemLabel = "Non-Certified Roadway"
        Case 1: FunctionalSystemLabel = "Interstate"
        Case 2: FunctionalSystemLabel = "Other Freeway"
        Case 3: FunctionalSystemLabel = "Other Principal Arterial"
        Case 4: FunctionalSystemLabel = "Minor Arterial"
        Case 5: FunctionalSystemLabel = "Major Collector"
        Case 6: FunctionalSystemLabel = "Minor Collector"
        Case 7: FunctionalSystemLabel = "Local"
        Case Else: FunctionalSystemLabel = "Unknown (" & code & ")"
    End Select
End Function

' Wisconsin's local-roads layer (REST_WI_LOCAL_ROADS) encodes urban/rural
' directly into FNCT_CLS_CTGY_TYCD instead of carrying a bare FHWA code
' (confirmed live via the layer's renderer uniqueValueInfos, §4.2b):
'   10 Rural Principal Arterial   60 Urban Principal Arterial
'   20 Rural Minor Arterial       86 Urban Minor Arterial Other
'   30 Rural Major Collector      96 Urban Collector Other
'   40 Rural Minor Collector
'   45 Rural Local                97 Urban Local
' "Urban Collector Other" (96) doesn't distinguish major vs minor collector.
' That split only changes the federal-aid verdict for RURAL collectors (rural
' major = federal aid, rural minor = not) - every *urban* collector is federal
' aid regardless of major/minor, so mapping 96 to Major Collector (5) is safe
' either way. ACUB (not this field) remains the source of truth for the
' Urban/Rural column; the rural/urban half of each code is discarded here.
Public Function WisconsinLocalCategoryToFhwa(ByVal categoryCode As Long) As Long
    Select Case categoryCode
        Case 10, 60: WisconsinLocalCategoryToFhwa = 3    ' Principal Arterial
        Case 20, 86: WisconsinLocalCategoryToFhwa = 4    ' Minor Arterial
        Case 30, 96: WisconsinLocalCategoryToFhwa = 5    ' Major Collector (96 = Urban Collector, major/minor unresolved)
        Case 40: WisconsinLocalCategoryToFhwa = 6         ' Rural Minor Collector
        Case 45, 97: WisconsinLocalCategoryToFhwa = 7     ' Local
        Case Else: WisconsinLocalCategoryToFhwa = 0       ' unrecognized - flagged for manual review
    End Select
End Function
